version: "2"
linters:
  enable:
    - revive
    - contextcheck
    - nilerr
    - unconvert
    - godoclint
  
  settings:
    revive:
      rules:
      - name: package-comments
        disabled: true