version: "2"
linters:
  enable:
    - revive
    - contextcheck
    - nilerr
    - unconvert
    - godoclint
    - misspell
  
  settings:
    revive:
      rules:
      - name: package-comments
        disabled: true
    godoclint:
      default: all
