FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY cmd ./cmd
COPY internal ./internal
RUN CGO_ENABLED=0 GOOS=linux go build -o /bin/app ./cmd/veripass/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /bin/app /bin/app
RUN adduser -D appuser
USER appuser
EXPOSE 8000
CMD ["/bin/app"]