ARG GO_VERSION=alpine

FROM golang:${GO_VERSION} AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN --mount=type=cache,target=/go/pkg go mod download
COPY cmd ./cmd
COPY internal ./internal
RUN --mount=type=cache,target=/root/.cache/go-build CGO_ENABLED=0 GOOS=linux go build -o /bin/app ./cmd/veripass/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /bin/app /bin/app
RUN adduser -D appuser
USER appuser
EXPOSE 8000
CMD ["/bin/app"]