// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/chetan0402/veripass/internal/ent/pass"
	"github.com/google/uuid"
)

// PassCreate is the builder for creating a Pass entity.
type PassCreate struct {
	config
	mutation *PassMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (pc *PassCreate) SetUserID(s string) *PassCreate {
	pc.mutation.SetUserID(s)
	return pc
}

// SetType sets the "type" field.
func (pc *PassCreate) SetType(pa pass.Type) *PassCreate {
	pc.mutation.SetType(pa)
	return pc
}

// SetNillableType sets the "type" field if the given value is not nil.
func (pc *PassCreate) SetNillableType(pa *pass.Type) *PassCreate {
	if pa != nil {
		pc.SetType(*pa)
	}
	return pc
}

// SetStartTime sets the "start_time" field.
func (pc *PassCreate) SetStartTime(t time.Time) *PassCreate {
	pc.mutation.SetStartTime(t)
	return pc
}

// SetEndTime sets the "end_time" field.
func (pc *PassCreate) SetEndTime(t time.Time) *PassCreate {
	pc.mutation.SetEndTime(t)
	return pc
}

// SetNillableEndTime sets the "end_time" field if the given value is not nil.
func (pc *PassCreate) SetNillableEndTime(t *time.Time) *PassCreate {
	if t != nil {
		pc.SetEndTime(*t)
	}
	return pc
}

// SetID sets the "id" field.
func (pc *PassCreate) SetID(u uuid.UUID) *PassCreate {
	pc.mutation.SetID(u)
	return pc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (pc *PassCreate) SetNillableID(u *uuid.UUID) *PassCreate {
	if u != nil {
		pc.SetID(*u)
	}
	return pc
}

// Mutation returns the PassMutation object of the builder.
func (pc *PassCreate) Mutation() *PassMutation {
	return pc.mutation
}

// Save creates the Pass in the database.
func (pc *PassCreate) Save(ctx context.Context) (*Pass, error) {
	pc.defaults()
	return withHooks(ctx, pc.sqlSave, pc.mutation, pc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pc *PassCreate) SaveX(ctx context.Context) *Pass {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pc *PassCreate) Exec(ctx context.Context) error {
	_, err := pc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pc *PassCreate) ExecX(ctx context.Context) {
	if err := pc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pc *PassCreate) defaults() {
	if _, ok := pc.mutation.GetType(); !ok {
		v := pass.DefaultType
		pc.mutation.SetType(v)
	}
	if _, ok := pc.mutation.ID(); !ok {
		v := pass.DefaultID()
		pc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pc *PassCreate) check() error {
	if _, ok := pc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Pass.user_id"`)}
	}
	if _, ok := pc.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Pass.type"`)}
	}
	if v, ok := pc.mutation.GetType(); ok {
		if err := pass.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Pass.type": %w`, err)}
		}
	}
	if _, ok := pc.mutation.StartTime(); !ok {
		return &ValidationError{Name: "start_time", err: errors.New(`ent: missing required field "Pass.start_time"`)}
	}
	return nil
}

func (pc *PassCreate) sqlSave(ctx context.Context) (*Pass, error) {
	if err := pc.check(); err != nil {
		return nil, err
	}
	_node, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	pc.mutation.id = &_node.ID
	pc.mutation.done = true
	return _node, nil
}

func (pc *PassCreate) createSpec() (*Pass, *sqlgraph.CreateSpec) {
	var (
		_node = &Pass{config: pc.config}
		_spec = sqlgraph.NewCreateSpec(pass.Table, sqlgraph.NewFieldSpec(pass.FieldID, field.TypeUUID))
	)
	if id, ok := pc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := pc.mutation.UserID(); ok {
		_spec.SetField(pass.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := pc.mutation.GetType(); ok {
		_spec.SetField(pass.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := pc.mutation.StartTime(); ok {
		_spec.SetField(pass.FieldStartTime, field.TypeTime, value)
		_node.StartTime = value
	}
	if value, ok := pc.mutation.EndTime(); ok {
		_spec.SetField(pass.FieldEndTime, field.TypeTime, value)
		_node.EndTime = value
	}
	return _node, _spec
}

// PassCreateBulk is the builder for creating many Pass entities in bulk.
type PassCreateBulk struct {
	config
	err      error
	builders []*PassCreate
}

// Save creates the Pass entities in the database.
func (pcb *PassCreateBulk) Save(ctx context.Context) ([]*Pass, error) {
	if pcb.err != nil {
		return nil, pcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(pcb.builders))
	nodes := make([]*Pass, len(pcb.builders))
	mutators := make([]Mutator, len(pcb.builders))
	for i := range pcb.builders {
		func(i int, root context.Context) {
			builder := pcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PassMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pcb *PassCreateBulk) SaveX(ctx context.Context) []*Pass {
	v, err := pcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pcb *PassCreateBulk) Exec(ctx context.Context) error {
	_, err := pcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcb *PassCreateBulk) ExecX(ctx context.Context) {
	if err := pcb.Exec(ctx); err != nil {
		panic(err)
	}
}
