// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Admin is the predicate function for admin builders.
type Admin func(*sql.Selector)

// Pass is the predicate function for pass builders.
type Pass func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
